config/routes.rb
Flowers::Application.routes.draw do
  resources :locations

  resources :line_items

  resources :carts

  get "gallery/index"
  get "gallery/checkout"
  get "gallery/search"
  resources :stores

  

  get "account/signup"
  get "account/login"
  get "account/forget_password"
  get "account/reset_password"
  get "account/index"

  get "signup" => "account#signup", :as => "signup"  
  get "login" => "account#login", :as => "login" 

  get ':controller(/:action(/:id))(.:format)'
  post ':controller(/:action(/:id))(.:format)'

end

app/models/store.rb
class Store < ActiveRecord::Base
	has_attached_file :image
	self.per_page = 3
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  #layout "application"
  
  before_filter :authorize
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    @stores =  Store.paginate(:page=>params[:page])
  end

def set_cart
      @cart = Cart.find(params[:id])
    end
  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:product_name, :product_type, :description, :price, :features, :image)
    end

    def authorize
      if session[:admin].nil?
      flash[:notice] = "Please log in"
      redirect_to :controller => :admin, :action => :login
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_field :features %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing Products</h1>
<div class="feat_prod_box_details">
      
  <table class="cart_table" width=550>
    <thead>
      <tr class="cart_title">
        <th style="width:25">Product name</th>
        <th>Product type</th>
       <!-- <th>Description</th>-->
        <th>Price</th>
        <th>Features</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td><%= store.product_name %></td>
          <td><%= store.product_type %></td>
          <!--<td><%= store.description %></td>-->
          <td><%= store.price %></td>
          <td><%= store.features %></td>
          <td><%= link_to 'Show', store %></td>
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>  
    </tbody>
  </table>
  <%= link_to 'New Product', new_store_path %>

  <div class="flickr_pagination">
      <div class="page_info">
        <%= page_entries_info @stores %>
      </div><br>
      <%= will_paginate @stores, :container => false %>
  </div>
</div>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<!--<p id="notice"><%= notice %></p> -->
<p>
  <b>Flower image:</b>
  <%= image_tag @store.image.url ,:height=>"200",:width=>"200"%>
</p>
<p>
  <strong>Product name:</strong>
  <%= @store.product_name %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @store.product_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@store.price) %>
</p>

<p>
  <strong>Features:</strong>
  <%= @store.features %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>
        
          