config/routes.rb
Flowers::Application.routes.draw do
  resources :locations

  resources :line_items

  resources :carts

  get "gallery/index"
  get "gallery/checkout"
  get "gallery/search"
  resources :stores

  

  get "account/signup"
  get "account/login"
  get "account/forget_password"
  get "account/reset_password"
  get "account/index"

  get "signup" => "account#signup", :as => "signup"  
  get "login" => "account#login", :as => "login" 

  get ':controller(/:action(/:id))(.:format)'
  post ':controller(/:action(/:id))(.:format)'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :line_items, :dependent => :destroy

def add_product(store_id)
	current_item = line_items.find_by_store_id(store_id)
	if current_item
		current_item.quantity += 1
	else
		current_item = line_items.build(:store_id => store_id)
	end
	current_item
end

def total_price
	line_items.to_a.sum { |item| item.total_price }
end 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :set_cart, only: [:edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #Add To Cart
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        logger.error "Attempt to access invalid cart #{params[:id]}"
        redirect_to @cart, :notice => 'Invalid Cart'
      else
        respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
     end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }        
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }        
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
=begin
0  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
=end
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy    
    redirect_to :controller => "gallery", :action => "index"
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!--<div class="title">
	<span class="title_icon">
		<img src="/assets/bullet1.gif" alt="" />
	</span>Your cart
</div>-->
<div class="feat_prod_box_details">
	<% unless cart.line_items.empty? %>
	    <table class="cart_table">
	    	<tr class="cart_title">
				<!--<td>Item pic</td>-->
		        <td style="width:10">Product name</td>
		        <td>Unit price</td>
		        <td>Qty</td>
		        <td>Total</td>
		        <td></td>
		    </tr     
			<%= render(cart.line_items) %>
			<tr>
				<td colspan="4" class="cart_total"><span class="red">TOTAL PRICE:</span></td>
				<td class="total_cell"><%= number_to_currency(cart.total_price)  %></td>
			</tr>
		</table>
		<%= button_to 'Empty Cart', cart, :method => :delete,:class=>"continue", :confirm => 'Are you sure?' %>		
			<a href="/gallery/index" class="continue">&lt; continue</a> | 
			<% unless session[:user].nil? %>				
				<%= link_to "Checkout" , :class=>"checkout", controller: "gallery", action: "checkout", amount:cart.total_price %>
			<% else %>
				<a href="/account/login" class="checkout">checkout&gt;</a>
			<% end %>
		
	<% end %>     
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table class="cart_table" width=300>
  <thead>
    <tr>
      <th ></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!--
<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>
-->

<%= render @cart %>